version: "3.9"
services:
  monolith:
    build: ./
    image: monolith
    healthcheck:
      test: curl --fail http://localhost || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
  haproxy:
    build: $PWD/haproxy
    image: haproxy
    ports:
      - "80:80"
      - "8404:8404"
    volumes:
      - "./haproxy:/usr/local/etc/haproxy:ro"

networks:
  default:
    driver: bridge