version: "3.9"
services:
  users:
    image: jh7939/microservices:users_microservice
    networks:
      - my-network
    healthcheck:
      test: curl --fail http://localhost/api/users || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
  threads:
    image: jh7939/microservices:threads_microservice
    networks:
      - my-network
    healthcheck:
      test: curl --fail http://localhost/api/threads || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
  posts:
    image: jh7939/microservices:posts_microservice
    networks:
      - my-network
    healthcheck:
      test: curl --fail http://localhost/api/posts || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
  comments:
    image: jh7939/microservices:comments_microservice
    networks:
      - my-network
    healthcheck:
      test: curl --fail http://localhost/api/comments || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
  newservice:
    image: jh7939/microservices:newservice_microservice
    networks:
      - my-network
    healthcheck:
      test: curl --fail http://localhost/api/newservice%7C%7C exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
  newservice2:
    image: jh7939/microservices:newservice2_microservice
    networks:
      - my-network
    healthcheck:
      test: curl --fail http://localhost/api/newservice2%7C%7C exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
  newservice3:
    image: jh7939/microservices:newservice3_microservice
    networks:
      - my-network
    healthcheck:
      test: curl --fail http://localhost/api/newservice3%7C%7C exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
  haproxy:
    image: jh7939/microservices:haproxy
    networks:
      - my-network
    ports:
      - "80:80"
      - "8404:8404"
      - "5555:5555"
    volumes:
      - "./haproxy:/usr/local/etc/haproxy:rw"
networks:
  my-network:
    driver: bridge
